# Modbus Controller Module Makefile
obj-m += modbus_controller_module.o
modbus_controller_module-y := modbuscontroller.o \
								 modbuscontroller_timer.o \
								 modbus_rtu/mbrtu.o \
								 modbus_rtu/port_event.o \
								 modbus_rtu/port_timer.o \
								 modbus_rtu/modbus.o \
								 modbus_rtu/mbcrc.o
